// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieMatchApp.Data;

#nullable disable

namespace MovieMatchApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260428192430_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("MovieMatchApp.Models.Mood", b =>
                {
                    b.Property<int>("MoodID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoodName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MoodID");

                    b.ToTable("Moods");
                });

            modelBuilder.Entity("MovieMatchApp.Models.Movie", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Runtime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieMatchApp.Models.RandomSelection", b =>
                {
                    b.Property<int>("RandomselectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("RandomselectionID");

                    b.HasIndex("MovieID");

                    b.HasIndex("UserID");

                    b.ToTable("RandomSelections");
                });

            modelBuilder.Entity("MovieMatchApp.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieMatchApp.Models.Watchlist", b =>
                {
                    b.Property<int>("WatchlistID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<int>("MoodID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WatchStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("WatchlistID");

                    b.HasIndex("MoodID");

                    b.HasIndex("MovieID");

                    b.HasIndex("UserID");

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("MovieMatchApp.Models.RandomSelection", b =>
                {
                    b.HasOne("MovieMatchApp.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieMatchApp.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieMatchApp.Models.Watchlist", b =>
                {
                    b.HasOne("MovieMatchApp.Models.Mood", "Mood")
                        .WithMany("Watchlists")
                        .HasForeignKey("MoodID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieMatchApp.Models.Movie", "Movie")
                        .WithMany("Watchlists")
                        .HasForeignKey("MovieID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieMatchApp.Models.User", "User")
                        .WithMany("Watchlists")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mood");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieMatchApp.Models.Mood", b =>
                {
                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("MovieMatchApp.Models.Movie", b =>
                {
                    b.Navigation("Watchlists");
                });

            modelBuilder.Entity("MovieMatchApp.Models.User", b =>
                {
                    b.Navigation("Watchlists");
                });
#pragma warning restore 612, 618
        }
    }
}
